# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2017-01-30 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsez', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthdate',
            field=models.DateField(),
        ),
    ]
