# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 22:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responsez', '0002_auto_20170205_1805'),
        ('responsez', '0002_auto_20170130_2305'),
    ]

    operations = [
    ]
