# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-25 15:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsez', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 25, 18, 46, 49, 456000)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='typeNof',
            field=models.IntegerField(choices=[(0, 'addFriend'), (1, 'friendship_accomplished'), (2, 'eventInvite')]),
        ),
    ]
