# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-25 15:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsez', '0005_auto_20170325_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 25, 18, 47, 10, 348000)),
        ),
    ]
