# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-10 13:59
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('responsez', '0006_auto_20170325_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'invited'), (1, 'going'), (2, 'maybe'), (3, 'not_going')])),
            ],
        ),
        migrations.CreateModel(
            name='BaseEvent',
            fields=[
                ('event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('invites', models.ManyToManyField(through='responsez.AttendStatus', to='responsez.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='NormalEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 10, 13, 59, 28, 870000)),
        ),
        migrations.AddField(
            model_name='attendstatus',
            name='baseevent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responsez.BaseEvent'),
        ),
        migrations.AddField(
            model_name='attendstatus',
            name='userprofile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responsez.UserProfile'),
        ),
    ]
