# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-10 13:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsez', '0007_auto_20170510_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 10, 13, 59, 42, 91000)),
        ),
    ]
