# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-10 15:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsez', '0011_auto_20170510_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='normalevent',
            name='baseevent_ptr',
        ),
        migrations.AddField(
            model_name='baseevent',
            name='location',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baseevent',
            name='title',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 10, 15, 40, 51, 260000)),
        ),
        migrations.DeleteModel(
            name='NormalEvent',
        ),
    ]
